trailingComma: "es5"
semi: true
singleQuote: false
plugins:
  - "@trivago/prettier-plugin-sort-imports"
importOrder:
  - "^bun$"
  - "^bun:test$"
  - "^node:.*"
  - "<THIRD_PARTY_MODULES>"
  - "^@drsmile1001/.*"
  - "^[./]"
importOrderSeparation: true
importOrderSortSpecifiers: true
